// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0XPvducN-XtBAqMpxUbjKjOS9g34c-yw',
    appId: '1:952818259893:web:d38e0e3e97319b4c092bfc',
    messagingSenderId: '952818259893',
    projectId: 'tokopedia-paste',
    authDomain: 'tokopedia-paste.firebaseapp.com',
    storageBucket: 'tokopedia-paste.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb--3TpZi3YCbdlhuCIEF7xZY-6vOqeoU',
    appId: '1:952818259893:android:772dd5e8585fae87092bfc',
    messagingSenderId: '952818259893',
    projectId: 'tokopedia-paste',
    storageBucket: 'tokopedia-paste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApipgoEfg4wMQ4JavzsIlbxN2mLj1xx7k',
    appId: '1:952818259893:ios:465decbee98ab890092bfc',
    messagingSenderId: '952818259893',
    projectId: 'tokopedia-paste',
    storageBucket: 'tokopedia-paste.appspot.com',
    iosClientId: '952818259893-bkitnib36r4rhsc3baqd4eg0ftv4lc79.apps.googleusercontent.com',
    iosBundleId: 'com.tokopedia.tokopedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApipgoEfg4wMQ4JavzsIlbxN2mLj1xx7k',
    appId: '1:952818259893:ios:465decbee98ab890092bfc',
    messagingSenderId: '952818259893',
    projectId: 'tokopedia-paste',
    storageBucket: 'tokopedia-paste.appspot.com',
    iosClientId: '952818259893-bkitnib36r4rhsc3baqd4eg0ftv4lc79.apps.googleusercontent.com',
    iosBundleId: 'com.tokopedia.tokopedia',
  );
}
